/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApplicationForm {
    id: bigint;
    preferredStartDate: string;
    name: string;
    careerStatus: CareerStatus;
    email: string;
    motivationStatement: string;
    program: Program;
}
export enum CareerStatus {
    other = "other",
    youngProfessional = "youngProfessional",
    transitioning = "transitioning",
    student = "student"
}
export enum Program {
    aiDataAndAnalyticsEngineerAccelerator = "aiDataAndAnalyticsEngineerAccelerator",
    aiInfrastructureEngineerAccelerator = "aiInfrastructureEngineerAccelerator",
    qaTestingProgram = "qaTestingProgram"
}
export interface backendInterface {
    getAllApplications(): Promise<Array<ApplicationForm>>;
    getApplication(id: bigint): Promise<ApplicationForm>;
    submitApplication(program: Program, name: string, email: string, careerStatus: CareerStatus, motivationStatement: string, preferredStartDate: string): Promise<bigint>;
}
import type { ApplicationForm as _ApplicationForm, CareerStatus as _CareerStatus, Program as _Program } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllApplications(): Promise<Array<ApplicationForm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: bigint): Promise<ApplicationForm> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_ApplicationForm_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_ApplicationForm_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitApplication(arg0: Program, arg1: string, arg2: string, arg3: CareerStatus, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(to_candid_Program_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_CareerStatus_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(to_candid_Program_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_CareerStatus_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_ApplicationForm_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationForm): ApplicationForm {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CareerStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CareerStatus): CareerStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Program_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Program): Program {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    preferredStartDate: string;
    name: string;
    careerStatus: _CareerStatus;
    email: string;
    motivationStatement: string;
    program: _Program;
}): {
    id: bigint;
    preferredStartDate: string;
    name: string;
    careerStatus: CareerStatus;
    email: string;
    motivationStatement: string;
    program: Program;
} {
    return {
        id: value.id,
        preferredStartDate: value.preferredStartDate,
        name: value.name,
        careerStatus: from_candid_CareerStatus_n4(_uploadFile, _downloadFile, value.careerStatus),
        email: value.email,
        motivationStatement: value.motivationStatement,
        program: from_candid_Program_n6(_uploadFile, _downloadFile, value.program)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    youngProfessional: null;
} | {
    transitioning: null;
} | {
    student: null;
}): CareerStatus {
    return "other" in value ? CareerStatus.other : "youngProfessional" in value ? CareerStatus.youngProfessional : "transitioning" in value ? CareerStatus.transitioning : "student" in value ? CareerStatus.student : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiDataAndAnalyticsEngineerAccelerator: null;
} | {
    aiInfrastructureEngineerAccelerator: null;
} | {
    qaTestingProgram: null;
}): Program {
    return "aiDataAndAnalyticsEngineerAccelerator" in value ? Program.aiDataAndAnalyticsEngineerAccelerator : "aiInfrastructureEngineerAccelerator" in value ? Program.aiInfrastructureEngineerAccelerator : "qaTestingProgram" in value ? Program.qaTestingProgram : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationForm>): Array<ApplicationForm> {
    return value.map((x)=>from_candid_ApplicationForm_n2(_uploadFile, _downloadFile, x));
}
function to_candid_CareerStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerStatus): _CareerStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Program_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): _Program {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CareerStatus): {
    other: null;
} | {
    youngProfessional: null;
} | {
    transitioning: null;
} | {
    student: null;
} {
    return value == CareerStatus.other ? {
        other: null
    } : value == CareerStatus.youngProfessional ? {
        youngProfessional: null
    } : value == CareerStatus.transitioning ? {
        transitioning: null
    } : value == CareerStatus.student ? {
        student: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): {
    aiDataAndAnalyticsEngineerAccelerator: null;
} | {
    aiInfrastructureEngineerAccelerator: null;
} | {
    qaTestingProgram: null;
} {
    return value == Program.aiDataAndAnalyticsEngineerAccelerator ? {
        aiDataAndAnalyticsEngineerAccelerator: null
    } : value == Program.aiInfrastructureEngineerAccelerator ? {
        aiInfrastructureEngineerAccelerator: null
    } : value == Program.qaTestingProgram ? {
        qaTestingProgram: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
