/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplicationForm {
  'id' : bigint,
  'preferredStartDate' : string,
  'name' : string,
  'careerStatus' : CareerStatus,
  'email' : string,
  'motivationStatement' : string,
  'program' : Program,
}
export type CareerStatus = { 'other' : null } |
  { 'youngProfessional' : null } |
  { 'transitioning' : null } |
  { 'student' : null };
export type Program = { 'aiDataAndAnalyticsEngineerAccelerator' : null } |
  { 'aiInfrastructureEngineerAccelerator' : null } |
  { 'qaTestingProgram' : null };
export interface _SERVICE {
  'getAllApplications' : ActorMethod<[], Array<ApplicationForm>>,
  'getApplication' : ActorMethod<[bigint], ApplicationForm>,
  'submitApplication' : ActorMethod<
    [Program, string, string, CareerStatus, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];