/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CareerStatus = IDL.Variant({
  'other' : IDL.Null,
  'youngProfessional' : IDL.Null,
  'transitioning' : IDL.Null,
  'student' : IDL.Null,
});
export const Program = IDL.Variant({
  'aiDataAndAnalyticsEngineerAccelerator' : IDL.Null,
  'aiInfrastructureEngineerAccelerator' : IDL.Null,
  'qaTestingProgram' : IDL.Null,
});
export const ApplicationForm = IDL.Record({
  'id' : IDL.Nat,
  'preferredStartDate' : IDL.Text,
  'name' : IDL.Text,
  'careerStatus' : CareerStatus,
  'email' : IDL.Text,
  'motivationStatement' : IDL.Text,
  'program' : Program,
});

export const idlService = IDL.Service({
  'getAllApplications' : IDL.Func([], [IDL.Vec(ApplicationForm)], ['query']),
  'getApplication' : IDL.Func([IDL.Nat], [ApplicationForm], ['query']),
  'submitApplication' : IDL.Func(
      [Program, IDL.Text, IDL.Text, CareerStatus, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CareerStatus = IDL.Variant({
    'other' : IDL.Null,
    'youngProfessional' : IDL.Null,
    'transitioning' : IDL.Null,
    'student' : IDL.Null,
  });
  const Program = IDL.Variant({
    'aiDataAndAnalyticsEngineerAccelerator' : IDL.Null,
    'aiInfrastructureEngineerAccelerator' : IDL.Null,
    'qaTestingProgram' : IDL.Null,
  });
  const ApplicationForm = IDL.Record({
    'id' : IDL.Nat,
    'preferredStartDate' : IDL.Text,
    'name' : IDL.Text,
    'careerStatus' : CareerStatus,
    'email' : IDL.Text,
    'motivationStatement' : IDL.Text,
    'program' : Program,
  });
  
  return IDL.Service({
    'getAllApplications' : IDL.Func([], [IDL.Vec(ApplicationForm)], ['query']),
    'getApplication' : IDL.Func([IDL.Nat], [ApplicationForm], ['query']),
    'submitApplication' : IDL.Func(
        [Program, IDL.Text, IDL.Text, CareerStatus, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };